seed: 42

data:
  dataset: bwfolder
  path: seismic_velocity
  channels: 1
  image_size: 256
  random_flip: false

method: dlpm

dlpm:
  alpha: 1.8
  reverse_steps: 1000
  isotropic: true
  mean_predict: EPSILON
  rescale_timesteps: true
  var_predict: FIXED
  scale: scale_preserving
  input_scaling: false

eval:
  data_to_generate: 64
  batch_size: 4
  real_data: 64
  dlpm:
    deterministic: false
    dlim_eta: 0.0
    reverse_steps: 1000
    clip_denoised: false
    clamp_a: 20
    clamp_eps: 200

model:
  model_type: ddpm
  attn_resolutions: [8, 16]
  channel_mult: [1, 2, 4, 4]
  dropout: 0.0
  model_channels: 64
  num_heads: 4
  num_res_blocks: 2
  learn_variance: false

training:
  batch_size: 4
  num_workers: 0
  dlpm:
    ema_rates: [0.9999]
    grad_clip: 1.0
    loss_monte_carlo: mean
    loss_type: EPS_LOSS
    lploss: 2.0
    monte_carlo_inner: 1
    monte_carlo_outer: 1
    clamp_a: 20
    clamp_eps: 200

optim:
  optimizer: adamw
  schedule: linear
  lr: 0.0002
  warmup: 1000
  lr_steps: 100000
  lr_step_size: 1000
  lr_gamma: 0.99

run:
  epochs: 100
  eval_freq: 25
  checkpoint_freq: 50
  progress: true
